name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true      
      - run: bundle install
      - run: bundle exec rake spec
      - run: bundle exec rspec
